baseURL = "https://pubsub.club/"
languageCode = "en-us"
title = "Pub Sub of the Week"
description = ""
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[outputFormats]
  [outputFormats.CACHE]
  mediaType = "application/json"
  baseName = "cache"
  isPlainText = true
  notAlternative = true

[outputs]
home = [
  "HTML",
  "CACHE"
]

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0
