[build]
base = "./"
publish = "./public"
command = "hugo --gc --minify --ignoreCache"
functions = "./functions"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "0.57.2"

[[redirects]]
from = "/api"
to = "https://pubsub.club/.netlify/functions/getSub"
status = 200

[[redirects]]
from = "/cache"
to = "https://pubsub.club/cache.json"
status = 200
